
FROM ubuntu:25.10

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    openssh-client \
    g++ \
    sudo \
    vim \
    wget \
    qt6-base-dev \
    qt6-5compat-dev \
    libxcb-cursor0 \
    gdb \
    gdbserver \
    linux-tools-common \
    valgrind \
    x11-apps \
    xterm \
    clangd \
    clang-tidy \
    clazy \
    qbs \
    cmake \
    ninja-build
